- name: Dem removing docker containers from Ansible
  hosts: localhost
  
  tasks: 
   - name: Remove all Ubuntu Container
     docker_container: 
       name: "ubuntu{{item}}"
       hostname: "ubuntu{{item}}"
       image: "verizon/ansible-ubuntu"
       state: absent 
     with_sequence: count=3
     #with_sequence: start=1 end=3

   - name: Remove all CentOS Container
     docker_container: 
       name: "centos{{item}}"
       hostname: "centos{{item}}"
       image: "verizon/ansible-centos"
       state: absent 
     with_sequence: count=3
     #with_sequence: start=1 end=3

   - name: Remove all remaining containers
     shell: "docker rm -f $(docker ps -aq)"
     ignore_errors: True 
